<?php if ($block->isCallForPrice()): 
$product = $block->getProduct();
?>  
 
                                                                       
<?php $buttonTitle = $block->getButtonTitle(); ?>  
<button type="button"  data-bind="click: function(){ showPopup(<?php echo $product->getId()?>); }"
                    title="<?= /* @escapeNotVerified */ $buttonTitle ?>"
                    class="action primary tocart"
                    id="product-callforprice-button">
                <span><?= /* @escapeNotVerified */ $buttonTitle ?></span>
</button> 
 
<?php endif;?> 